[build]
  command = "npm run netlify-build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuração para o Next.js
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/adapter-pg"]

# Redirecionamentos
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Configuração para o Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Configuração de headers para API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"

# Configuração de headers para assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
