[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://api.controle-carga.com"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
